name: "release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Укажите версию (ОСТАВЬТЕ ПУСТЫМ, чтобы взять текущую версию из package.json)'
        required: false
        default: ''

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          scope: "@mrs-soft"

      - name: enable corepack
        run: corepack enable
        shell: bash
      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-yarn-
      - run: yarn install

      - name: Set Package Version
        run: |
          INPUT_VERSION="${{ github.event.inputs.version }}"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          if [ -z "$INPUT_VERSION" ]; then
            echo "Поле пустое. Используем текущую версию из package.json: $CURRENT_VERSION"
          elif [ "$INPUT_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Введенная версия совпадает с текущей ($CURRENT_VERSION). Пропускаем обновление."
          else
            echo "Обновляем версию с $CURRENT_VERSION на $INPUT_VERSION..."
            npm version $INPUT_VERSION --no-git-tag-version
          fi
        shell: bash

      - name: Compile Library JS/TS
        run: yarn bob build

      - name: Publish to GitHub Packages
        run: npm publish --tag=mrs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}